In [2]:
import numpy as np
import math
from numpy import *

In [3]:
#elementos orbitales
rad=np.pi/180.0
omega=0.0*rad
inc=45.0*rad
w=20.0*rad
#elementos geometricos
a=7016*10**3
e=0.05
g=6.67*10**(-11.0)
mu=g*5.97*10**24
p=a*(1-e**2)

In [4]:
#matris de rotacion, angulos en radianes
def rotacion(omega,inc,w):
    rot1=np.array([[np.cos(omega),-np.sin(omega),0.0],
             [np.sin(omega),np.cos(omega),0.0],
             [0.0,0.0,1.0]])
    rot2=np.array([[1.0,0.0,0.0],
               [0.0,np.cos(inc),-np.sin(inc)],
               [0.0,np.sin(inc),np.cos(inc)]])
    rot3=np.array([[np.cos(w),-np.sin(w),0.0],
             [np.sin(w),np.cos(w),0.0],
             [0.0,0.0,1.0]])
    rot_final=(rot1.dot(rot2)).dot(rot3)
    return rot_final

In [8]:
rot_final=rotacion(omega,inc,w)
print rot_final

[[ 0.93969262 -0.34202014  0.        ]
 [ 0.24184476  0.66446302 -0.70710678]
 [ 0.24184476  0.66446302  0.70710678]]


In [9]:
#posicion
rm=66700.25365*10**3.0 #en metros
f=10*rad
r=np.array([rm*np.cos(f),rm*np.sin(f),0.0])
r_rotado=rot_final.dot(r)
print r_rotado

[ 57764114.09976573  23582100.83138888  23582100.83138888]


In [10]:
#velosidad
mag=-(mu/p)**0.5
vi=mag*np.sin(f)
vj=-mag*(e-np.cos(f))
vel=np.array([vi,vj,0.0])
v_rotada=rot_final.dot(vel)
print v_rotada

[ 1180.84817456 -5002.1277423  -5002.1277423 ]
